  var translations_pt_br = {
		HOME:	"Início",
		SETTINGS:	"Configurações",
		LOGOUT:	"Sair",
  	ADMINISTRATORS: "Administradores",
		ADD_ADMINISTRATOR:	"Adicionar Administrador",
		DELETE_SELECTED:	"Excluir selecionado",
		SELECT_ALL:	"Selecionar todos",
		FIRST_NAME:	"Primeiro nome",
		LAST_NAME:	"Sobrenome",
		LOGIN: "Entrar",
		EMAIL:	"Email",
		PASSWORD:	"Senha",
		ERROR_LOGIN:	"Erro ao entrar",
		ARE_YOU_SURE:	"Você tem certeza?",
		CONFIRM_DELETE_PERSON:	"Confirmar excluir pessoa",
		YES:	"Sim",
		NO:	"Não",
		NO_PEOPLE:	"Não há pessoas",
		ATTENDEES:	"Participantes",
		ADD_ATTENDEE:	"Adicionar participantes",
		SEARCH:	"Buscar",
		ATTENDED:	"Credenciado",
		ACCREDIT:	"Descredenciado",
		WORKSHOPS:	"Workshops",
		SPEECHES:	"Palestras",
		MINICOURSES:	"Minicursos",
		ADD_SPEAKER:	"Adicionar palestrante",
		COMPANY:	"Empresa",
		ROLE:	"Cargo",
		SPEAKERS:	"Palestrantes"
};

var translations_en_us = {
	HOME:	"Home",
	SETTINGS:	"Settings",
	LOGOUT:	"Logout",
	ADMINISTRATORS: "Administrators",
	ADD_ADMINISTRATOR:	"Add administrator",
	DELETE_SELECTED:	"Delete selected",
	SELECT_ALL: "Select all",
	FIRST_NAME: "First name",
	LAST_NAME: "Last name",
	LOGIN:	"Login",
	EMAIL:	"Email",
	PASSWORD:	"Password",
	ERROR_LOGIN:	"Login error",
	ARE_YOU_SURE:	"Are you sure?",
	CONFIRM_DELETE_PERSON:	"Confrim delete person",
	YES:	"Yes",
	NO:	"No",
	NO_PEOPLE:	"No people",
	ATTENDEES:	"Attendees",
	ADD_ATTENDEE:	"Add attendees",
	SEARCH:	"Search",
	ATTENDED:	"Attended",
	ACCREDIT:	"Accredit",
	WORKSHOPS:	"Workshops",
	SPEECHES:	"Speeches",
	MINICOURSES:	"Minicourses",
	ADD_SPEAKER:	"Add speaker",
	COMPANY:	"Company",
	ROLE:	"Role",
	SPEAKERS:	"Speakers"
};


var translations_es_es = {
	HOME:	"Inicio",
	SETTINGS:	"Ajustes",
	LOGOUT:	"Cerrar sesión",
	ADMINISTRATORS:	"Administradores",
	ADD_ADMINISTRATOR:	"Agregar administrador",
	DELETE_SELECTED:	"Eliminar seleccionado",
	SELECT_ALL:	"Seleccionar todo",
	FIRST_NAME:	"Primero nombre",
	LAST_NAME:	"Apellido",
	LOGIN:	"Iniciar sesión",
	EMAIL:	"Email",
	PASSWORD:	"Contraseña",
	ERROR_LOGIN:	"Error de inicio de sesión",
	ARE_YOU_SURE:	"¿Estás seguro?",
	CONFIRM_DELETE_PERSON:	"Confirmar eliminar persona",
	YES:	"Sí",
	NO:	"No",
	NO_PEOPLE:	"Sin gente",
	ATTENDEES:	"Asistentes",
	ADD_ATTENDEE:	"Agregar asistentes",
	SEARCH:	"Buscar",
	ATTENDED:	"Acreditado",
	ACCREDIT:	"De-acreditado",
	WORKSHOPS:	"Talleres",
	SPEECHES:	"Conferencias",
	MINICOURSES:	"Cursos cortos",
	ADD_SPEAKER:	"Agregar hablante",
	COMPANY:	"Empresa",
	ROLE:	"Cargo",
	SPEAKERS:	"Hablantes"
};
